# API Keys
openai_api_key: "your-openai-api-key"
groq_api_key: "your-groq-api-key"
 
# Model Parameters
model_name: "mixtral-8x7b-32768"
temperature: 0.7
max_tokens: 1000
 
# File Paths
data_dir: "data"
vector_db_path: "vector_db"
 
# Chunk Size for Text Splitting
chunk_size: 1000
chunk_overlap: 200