# API Keys
openai_api_key: ${OPENAI_API_KEY}
groq_api_key: ${GROQ_API_KEY}
 
# Model Parameters
model_name: ${MODEL_NAME}
temperature: 0.7
max_tokens: 1000
 
# File Paths
data_dir: "data"
vector_db_path: ${VECTOR_Db} 
 
# Chunk Size for Text Splitting
chunk_size: 1000
chunk_overlap: 200